apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-interceptor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-interceptor
  template:
    metadata:
      labels:
        app: redis-interceptor
    spec:
      containers:
        - name: kv-store
          image: docker.io/redis
          ports:
            - containerPort: 5000
        - name: interceptor
          image: docker.io/spdocker81/interceptor:latest
          ports:
            - containerPort: 3000
          env:
            - name: HOST
              value: "kv-store:5000"
            - name: PORT
              value: "3000"
            - name: LOG_PATH
              value: "/app/logs/log.txt"
            - name: CR_LOGGING_PATH
              value: "/app/logs_CR/CR_log.txt"
