apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-checkpoint-binding
subjects:
  - kind: User
    name: kubelet-client
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kubelet-checkpoint-role
  apiGroup: rbac.authorization.k8s.io
