apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: redis
spec:
  containers:
    - name: redis-master
      image: docker.io/redis
      ports:
        - containerPort: 6379
      env:
        - name: ROLE
          value: "master"
    - name: redis-replica-1
      image: docker.io/redis
      args: ["--appendonly", "yes", "--replicaof", "redis-master", "6379"]
      ports:
        - containerPort: 6379
      env:
        - name: ROLE
          value: "replica"
    - name: redis-replica-2
      image: docker.io/redis
      args: ["--appendonly", "yes", "--replicaof", "redis-master", "6379"]
      ports:
        - containerPort: 6379
      env:
        - name: ROLE
          value: "replica"
    - name: checkpoint-sidecar
      image: docker.io/library/criu-ubuntu:latest
      env:
        - name: ROLE
          value: "side-car"
      volumeMounts:
        - name: checkpoint-volume
          mountPath: /checkpoints
  volumes:
    - name: checkpoint-volume
      emptyDir: {}
