apiVersion: v1
kind: Service
metadata:
  name: interceptor
spec:
  selector:
    app: interceptor
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kv-store
spec:
  selector:
    app: kv-store
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
